gen_headers_[arm/arm64]: add linux/f2fs.h and drop unused headers
The failing command was run inside an sbox sandbox in temporary directory
out/soong/.temp/sbox/4b6c0e9a8773aa6a1c12bf25d53b7b1f1db2339d
The failing command line can be found in
out/soong/.temp/sbox/4b6c0e9a8773aa6a1c12bf25d53b7b1f1db2339d/sbox_command.0.bash
Headers to remove:
	media/cam_isp_tfe.h
	media/cam_tfe.h
	media/cam_ope.h
Headers to add:
	linux/msm_audio_wma.h
	sound/voice_params.h
	linux/msm_audio_amrwbplus.h
	linux/avtimer.h
	linux/msm_audio_alac.h
	linux/msm_audio_aac.h
	linux/msm_audio_amrnb.h
	sound/audio_slimslave.h
	linux/msm_audio_g711_dec.h
	linux/msm_audio_ac3.h
	linux/msm_audio_sbc.h
	linux/msm_audio_qcp.h
	linux/msm_audio_g711.h
	sound/msmcal-hwdep.h
	linux/msm_audio_ape.h
	sound/devdep_params.h
	linux/f2fs.h
	sound/msm-cirrus-playback.h
	linux/mfd/wcd9xxx/wcd9xxx_registers.h
	linux/msm_audio_mvs.h
	sound/lsm_params.h
	linux/msm_audio_wmapro.h
	sound/wcd-dsp-glink.h
	linux/msm_audio_amrwb.h
	linux/msm_audio_voicememo.h
	linux/wcd-spi-ac-params.h
	sound/cs35l41.h
	sound/audio_effects.h
	linux/mfd/wcd9xxx/wcd9320_registers.h
	linux/msm_audio.h
	linux/dm-user.h
	linux/msm_audio_calibration.h
error: gen_headers blueprints file is out of date, suggested fix:
 #######Please add or remove the above mentioned headers from kernel/xiaomi/sm7250/gen_headers_arm64.bp
then re-run the build
exit status 1